Todo
emit1892/js_todo pull request #1
Opened 2023-07-15 15:17 UTC by emit1892

## 課題のリンク
https://github.com/happiness-chain/practice/blob/main/13_javascript/002_todo_list.md

## やったこと
Vanilla JSで仕様内容に従いTodoListを作成しました。

## 動作確認方法
### Github Pages URL
https://emit1892.github.io/js_todo/

## その他
特になし。

2023-07-16 13:49 UTC, ihatov08 requested changes
何も入力しなくてもタスクが作成出来てしまうので修正お願いします！

2023-07-16 21:53 UTC, emit1892 commented
>

2023-07-16 22:19 UTC, emit1892 commented
@ihatov08 
何も入力がない場合、タスクが作成できないように修正しました。
https://github.com/emit1892/js_todo/pull/1/commits/36108db45afe1ee791bd22ecb32f431ad48f0b7e

また、その際発生したレイアウト崩れを修正しました。
https://github.com/emit1892/js_todo/pull/1/commits/5e4ef4e89ef1db7b8dff2814849da2101bd9158e

2023-07-17 13:30 UTC, ihatov08 approved these changes
確認しました、処理ごとに関数化していて 👍 だと思います、LGTMです！

2023-07-19 13:25 UTC, emit1892 commented
@ihatov08 
LGTMありがとうございます！

2023-07-19 13:25 UTC, merged